export const data = JSON.parse("{\"key\":\"v-d7764682\",\"path\":\"/framework/spring/2.html\",\"title\":\"Spring IOC\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Spring IOC\",\"tag\":[\"spring\"],\"prev\":\"./1\",\"next\":\"./3\",\"description\":\"Spring IOC\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://aurora-up.github.io/aurora-blog/framework/spring/2.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Aurora\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Spring IOC\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Spring IOC\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://aurora-up.github.io/aurora-blog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Spring IOC\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hdd\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"spring\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Spring IOC\\\",\\\"image\\\":[\\\"https://aurora-up.github.io/aurora-blog/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hdd\\\",\\\"url\\\":\\\"https://aurora-up.github.io/aurora-blog/\\\",\\\"email\\\":\\\"2723787996@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Spring IOC\",\"slug\":\"spring-ioc\",\"link\":\"#spring-ioc\",\"children\":[]},{\"level\":2,\"title\":\"向 IOC 容器中配置 bean\",\"slug\":\"向-ioc-容器中配置-bean\",\"link\":\"#向-ioc-容器中配置-bean\",\"children\":[{\"level\":3,\"title\":\"XML 配置\",\"slug\":\"xml-配置\",\"link\":\"#xml-配置\",\"children\":[]},{\"level\":3,\"title\":\"java 配置\",\"slug\":\"java-配置\",\"link\":\"#java-配置\",\"children\":[]},{\"level\":3,\"title\":\"注解配置\",\"slug\":\"注解配置\",\"link\":\"#注解配置\",\"children\":[]}]},{\"level\":2,\"title\":\"为 IOC 容器中的 bean 作依赖注入\",\"slug\":\"为-ioc-容器中的-bean-作依赖注入\",\"link\":\"#为-ioc-容器中的-bean-作依赖注入\",\"children\":[{\"level\":3,\"title\":\"Setter 注入\",\"slug\":\"setter-注入\",\"link\":\"#setter-注入\",\"children\":[]},{\"level\":3,\"title\":\"Constructor 注入\",\"slug\":\"constructor-注入\",\"link\":\"#constructor-注入\",\"children\":[]},{\"level\":3,\"title\":\"基于注解的注入\",\"slug\":\"基于注解的注入\",\"link\":\"#基于注解的注入\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.67,\"words\":1402},\"filePathRelative\":\"framework/spring/2.md\",\"excerpt\":\"<p>Spring IOC</p>\\n\",\"copyright\":{\"author\":\" hdd \",\"license\":\" MIT \"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
