export const data = JSON.parse("{\"key\":\"v-199fc5d4\",\"path\":\"/Algorithm/math/1.html\",\"title\":\"线性代数 —— 行列式\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"线性代数 —— 行列式\",\"category\":[\"数学\",\"线性代数\"],\"tag\":[\"行列式\"],\"description\":\"行列式的定义及性质 第一种定义 (本质定义) 对于一个二阶行列式，如下： $$ D_2 = \\\\left| \\\\begin{array} {cc} a{11} & a{12} \\\\\\\\ a{21} & a{22} \\\\\\\\ \\\\end{array} \\\\right| = a{11}a{22}-a{12}a{21} $$ 分别将第一行的的两个元素 $[a{11} , a...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://aurora-up.github.io/aurora-blog/Algorithm/math/1.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Aurora\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"线性代数 —— 行列式\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"行列式的定义及性质 第一种定义 (本质定义) 对于一个二阶行列式，如下： $$ D_2 = \\\\left| \\\\begin{array} {cc} a{11} & a{12} \\\\\\\\ a{21} & a{22} \\\\\\\\ \\\\end{array} \\\\right| = a{11}a{22}-a{12}a{21} $$ 分别将第一行的的两个元素 $[a{11} , a...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://aurora-up.github.io/aurora-blog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"线性代数 —— 行列式\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hdd\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"行列式\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"线性代数 —— 行列式\\\",\\\"image\\\":[\\\"https://aurora-up.github.io/aurora-blog/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hdd\\\",\\\"url\\\":\\\"https://aurora-up.github.io/aurora-blog/\\\",\\\"email\\\":\\\"2723787996@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"行列式的定义及性质\",\"slug\":\"行列式的定义及性质\",\"link\":\"#行列式的定义及性质\",\"children\":[{\"level\":3,\"title\":\"第一种定义 (本质定义)\",\"slug\":\"第一种定义-本质定义\",\"link\":\"#第一种定义-本质定义\",\"children\":[]},{\"level\":3,\"title\":\"第二种定义 (逆序数法定义)\",\"slug\":\"第二种定义-逆序数法定义\",\"link\":\"#第二种定义-逆序数法定义\",\"children\":[]},{\"level\":3,\"title\":\"第三种定义 (展开定理)\",\"slug\":\"第三种定义-展开定理\",\"link\":\"#第三种定义-展开定理\",\"children\":[]},{\"level\":3,\"title\":\"行列式的性质\",\"slug\":\"行列式的性质\",\"link\":\"#行列式的性质\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.46,\"words\":438},\"filePathRelative\":\"Algorithm/math/1.md\",\"excerpt\":\"\",\"copyright\":{\"author\":\" hdd \",\"license\":\" MIT \"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
